version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
